# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               SmartSprinkler
tagline:             'the simple solution'
description:         'An elegant <a href="http://jekyllrb.com" target="_blank">solution</a> for a dangerous problem.'
url:                 https://SmartSprinkler.com
baseurl:             '/SmartSprinklerSite'
paginate:            5
gems:				 [jekyll-paginate]

# About/contact
author:
  name:              Daniel Sahu
  url:               https://twitter.com/mdo
  email:             danielmohansahu@gmail.com

# Custom vars
version:             0.0.1
